# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=5000']
      - id: check-toml
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        description: 'Verifica padrão das importações'
        name: isort (python)
        args: ['--profile', 'black', '-c']
  - repo: https://github.com/pycqa/flake8
    rev: '6.0.0'
    hooks:
      - id: flake8
        description: 'Linter de python'
        exclude: ^.venv/
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        description: 'Formatação dos arquivos .py padrão black'
        exclude: migrations|apps|web
        args: ['--check', "--config", "./pyproject.toml"]
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        name: bandit
        exclude: ^tests/
        args:
          - -r
          - api
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        exclude: ˆmigrations/
        always_run: true

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 'v2.0.0'
    hooks:
      - id: conventional-pre-commit
        description: 'Confere o padrão do commit'
        stages: [commit-msg]
        args: [] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]
