version: '3.9'

x-common: &common
  env_file:
    - .env

  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

  networks:
    - main

services:
  flower:
    <<: *common
    image: mher/flower
    container_name: flower
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=${RABBITMQ_URL}

  api:
    <<: *common
    build: .
    environment:
      WORKERS: ${WORKERS:-2}
      THREADS: ${THREADS:-2}
    command: make migrate run.server.prod
    ports:
      - "${API_PORT}:80"
    depends_on:
      - pgbouncer
      - migrations
      - collectstatic
      - redis
      - rabbitmq
      - smtp4dev
    restart: always
    volumes:
      - .:/application

  db:
    <<: *common
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_INITDB_ARGS: --auth=md5
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgbouncer:
    <<: *common
    image: edoburu/pgbouncer:latest
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=1000
      - DEFAULT_POOL_SIZE=20
      - MIN_POOL_SIZE=5
      - RESERVE_POOL_SIZE=5
      - RESERVE_POOL_TIMEOUT=5
      - SERVER_RESET_QUERY=DISCARD ALL
      - SERVER_CHECK_QUERY=select 1
      - LOG_CONNECTIONS=1
      - LOG_DISCONNECTIONS=1
      - LOG_POOLER_ERRORS=1
      - STATS_PERIOD=60
      - AUTH_TYPE=md5
    volumes:
      - pgbouncer-data:/var/lib/pgbouncer

  redis:
    <<: *common
    image: redis:latest
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data

  rabbitmq:
    <<: *common
    image: rabbitmq:3-management
    restart: unless-stopped
    environment:
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - "${RABBITMQ_DASHBOARD_PORT:-15672}:15672"

  celery:
    <<: *common
    build: .
    command: make run.celery.local
    restart: unless-stopped
    depends_on:
      - api
      - redis
      - rabbitmq
    volumes:
      - .:/application

  migrations:
    <<: *common
    build: .
    command: make migrate
    depends_on:
      - db
    volumes:
      - .:/application

  collectstatic:
    <<: *common
    build: .
    command: make collectstatic
    depends_on:
      - db
    volumes:
      - .:/application

  smtp4dev:
    <<: *common
    image: rnwood/smtp4dev:v3
    ports:
      - "3000:80"
      - "2525:25"
    restart: always
    volumes:
      - smtp4dev-data:/var/smtp4dev

networks:
  main:
    ipam:
      driver: default

volumes:
  postgres-data:
  pgbouncer-data:
  redis-data:
  rabbitmq-data:
  smtp4dev-data:
