# Generated by Django 5.0.4 on 2024-04-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                related_name="events", to="core.participant"
            ),
        ),
    ]
