# Generated by Django 5.0.4 on 2024-04-10 18:28

import api.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_event_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    (api.core.models.EventStatus["DRAFT"], "draft"),
                    (api.core.models.EventStatus["PUBLISHED"], "published"),
                    (api.core.models.EventStatus["FILED"], "filed"),
                    (api.core.models.EventStatus["CANCELED"], "canceled"),
                    (api.core.models.EventStatus["CONCLUDED"], "concluded"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
