# Generated by Django 5.0.4 on 2024-04-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_event_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "rascunho"),
                    ("PUBLISHED", "publicado"),
                    ("FILED", "arquivado"),
                    ("CANCELED", "cancelado"),
                    ("CONCLUDED", "finalizado"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
